### ISSUE TITLE
urgent!!

### ISSUE THREAD

**Issue by bammy-A** [TDBankCanada/DevOps-#3]
<html>
<please see salary for AWS/Azure DevOps Engineer, the correct figure is $170USD
>

Strikethrough | ~~ ~~ |   | ~~This was mistaken text~~ | This was mistaken text
-- | -- | -- | -- | --

</please see salary for AWS/Azure DevOps Engineer, the correct figure is $170USD
y>
</html>

**Comment by Moisegermain** [comment]
@bammy-A is this correction referring to the confidential file?

**Comment by Yurmeposhe** [comment]
> @bammy-A is this correction referring to the confidential file?
Don't understand

**Comment by bammy-A** [comment]
> 

Yes, The salaries have now been reviewed
